# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'jazzy'

gem 'fastlane'

# A literal path (not a variable) — Dependabot rejects interpolated eval_gemfile arguments.
eval_gemfile("fastlane/Pluginfile")
