//
//  NSObject+TestSuite.h
//  ably
//
//  Created by Ricardo Pereira on 08/02/16.
//  Copyright © 2016 Ably. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "CompatibilityMacros.h"

/// `NSObject` extensions. Aspects lib allows you to add code to existing methods but it has some limitations with Swift because the NSInvocation is unavailable: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSInvocation_Class/
@interface NSObject (TestSuite)

ART_ASSUME_NONNULL_BEGIN

/// Get each return value generated by the identified instance method.
- (void)testSuite_getReturnValueFrom:(SEL)selector callback:(void (^)(id))callback;

/// Get argument at index from the identified instance method.
- (void)testSuite_getArgumentFrom:(SEL)selector atIndex:(NSInteger)index callback:(void (^)(id))callback;

/// Inject a block of code to the identified instance method.
- (void)testSuite_injectIntoMethod:(SEL)selector code:(void (^)(void))block;

ART_ASSUME_NONNULL_END

@end
