default_platform(:ios)

platform :ios do

  lane :test_iOS12 do
    run_tests(
      scheme: "Ably-iOS-Tests",
      derived_data_path: "derived_data",
      devices: ["iPhone XS (12.0)"],
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

  lane :test_iOS11 do
    run_tests(
      scheme: "Ably-iOS-Tests",
      derived_data_path: "derived_data",
      devices: ["iPhone 8 (11.4)"],
      test_without_building: false,
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

  lane :test_iOS10 do
    run_tests(
      scheme: "Ably-iOS-Tests",
      derived_data_path: "derived_data",
      devices: ["iPhone 7 (10.3.1)"],
      test_without_building: false,
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

  lane :test_iOS9 do
    run_tests(
      scheme: "Ably-iOS-Tests",
      derived_data_path: "derived_data",
      devices: ["iPhone 6 (9.3)"],
      test_without_building: false,
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

  lane :test_tvOS12 do
    run_tests(
      scheme: "Ably-tvOS-Tests",
      derived_data_path: "derived_data",
      devices: ["Apple TV 4K"],
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

  lane :test_macOS do
    run_tests(
      scheme: "Ably-macOS-Tests",
      derived_data_path: "derived_data",
      test_without_building: false,
      xcargs: { ABLY_ENV: ENV['ABLY_ENV'], CLANG_ANALYZER_OUTPUT: 'plist-html' }
    )
  end

end
