#import <Foundation/Foundation.h>
#import <Ably/ARTPush.h>

@class ARTDevicePushDetails;

NS_ASSUME_NONNULL_BEGIN

/**
 * BEGIN CANONICAL DOCSTRING
 * Contains the properties of a device registered for push notifications.
 * END CANONICAL DOCSTRING
 */
@interface ARTDeviceDetails : NSObject

/**
 * BEGIN CANONICAL DOCSTRING
 * A unique ID generated by the device.
 * END CANONICAL DOCSTRING
 */
@property (strong, nonatomic) ARTDeviceId *id;

/**
 * BEGIN CANONICAL DOCSTRING
 * The client ID the device is connected to Ably with.
 * END CANONICAL DOCSTRING
 */
@property (strong, nullable, nonatomic) NSString *clientId;

/**
 * BEGIN CANONICAL DOCSTRING
 * The [`DevicePlatform`]{@link DevicePlatform} associated with the device. Describes the platform the device uses, such as `android` or `ios`.
 * END CANONICAL DOCSTRING
 */
@property (strong, nonatomic) NSString *platform;
@property (strong, nonatomic) NSString *formFactor;
@property (strong, nonatomic) NSDictionary<NSString *, NSString *> *metadata;
@property (strong, nonatomic) ARTDevicePushDetails *push;

- (instancetype)init;
- (instancetype)initWithId:(ARTDeviceId *)deviceId;

@end

NS_ASSUME_NONNULL_END
