name: Carthage Installation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest

    env:
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      ABLY_ENV: sandbox

    steps:
      - name: Check out SDK repo
        uses: actions/checkout@v2
        
      - name: Select Specific Xcode Version (14.2)
        run: |
          sudo xcode-select -s /Applications/Xcode_14.2.app
          echo "Selected Xcode version:"
          xcodebuild -version

      - name: Log environment information
        run: ./Scripts/log-environment-information.sh

      - name: Reset Simulators
        run: xcrun simctl erase all
      
      - name: Carthage - Installation Test
        working-directory: ./Examples/AblyCarthage
        run:  |
          echo 'Installing Carthage dependencies...'
          carthage update --use-xcframeworks --platform iOS --no-use-binaries
          echo 'Building AblyCarthage example...'
          xcodebuild build -scheme "AblyCarthage" -destination "platform=iOS Simulator,name=iPhone 14" -configuration "Debug"
