name: Check Pod

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2

      - name: Select Specific Xcode Version (16.4)
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app
          echo "Selected Xcode version:"
          xcodebuild -version

      - name: Print Ruby version
        run: ruby --version
      - name: Print CocoaPods version
        run: 'echo -n "pod version: " && pod --version --verbose'
      - name: Print Make version
        run: make --version
      - name: Update dependencies
        run: make update
      - name: Validate pod
        run: pod lib lint
