# This workflow checks that the SPM version of the library (which includes additional code for plugin support compared to the Xcode version) compiles and does not have any warnings.

name: "Check SPM build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true
          persist-credentials: false
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: 16.4

      # https://forums.swift.org/t/warnings-as-errors-for-libraries-frameworks/58393/2
      - run: swift build -Xswiftc -warnings-as-errors
